In [1]:
import numpy as np
import pandas as pd
from learning_utils import pickle_load

/anaconda3/envs/cogtut/lib/python3.7/site-packages/rpy2/robjects/pandas2ri.py:17: FutureWarning: pandas.core.index is deprecated and will be removed in a future version.  The public classes are available in the top-level namespace.
  from pandas.core.index import Index as PandasIndex

In [2]:
d = "info_v1.0"
d2 = "info_v1.0_data"

In [3]:
import os
from collections import defaultdict
from IPython.display import display
ds = os.listdir(f"results/{d2}")
dis = defaultdict(list)
for d in ds:
    model = int(d.split("_")[-1].split(".")[0])
    dis[model].append(f"results/{d2}/{d}")
data = []
models = list(dis.keys())
for model in models:
    for d in dis[model][:1]:
        sim_data = pickle_load(d)
        info_data = sim_data['info']
        for trial_info_data in info_data:
            for click_info in trial_info_data:
                for c in click_info:
                    data.append([*c, model])
data_df = pd.DataFrame(data, columns=['info', 'node_value', 'pr', 'rpe', 'model'])
display(data_df)

         info  node_value   pr        rpe  model
0       False       -24.0  0.0  -1.127097   1809
1       False       -24.0  0.0  -0.749577   1809
2       False         8.0  0.0  -1.065364   1809
3       False        48.0  0.0  -2.147522   1809
4        True         0.0  0.0  42.534185   1809
...       ...         ...  ...        ...    ...
177936   True         0.0  0.0   0.000000   1804
177937   True         0.0  0.0   0.000000   1804
177938   True         0.0  0.0   0.000000   1804
177939   True         0.0  0.0   0.000000   1804
177940   True         0.0  0.0   0.000000   1804

[177941 rows x 5 columns]

In [5]:
data_df['info_present'] = data_df['info']
data_df['positive_value'] = data_df['node_value'] > 0
display(data_df)

         info  node_value   pr        rpe  model  positive_value  info_present
0       False       -24.0  0.0  -1.127097   1809           False         False
1       False       -24.0  0.0  -0.749577   1809           False         False
2       False         8.0  0.0  -1.065364   1809            True         False
3       False        48.0  0.0  -2.147522   1809            True         False
4        True         0.0  0.0  42.534185   1809           False          True
...       ...         ...  ...        ...    ...             ...           ...
177936   True         0.0  0.0   0.000000   1804           False          True
177937   True         0.0  0.0   0.000000   1804           False          True
177938   True         0.0  0.0   0.000000   1804           False          True
177939   True         0.0  0.0   0.000000   1804           False          True
177940   True         0.0  0.0   0.000000   1804           False          True

[177941 rows x 7 columns]

In [6]:
grouped_data_df = data_df.groupby(['positive_info', 'positive_value', 'model'])
display(grouped_data_df)

KeyError: 'positive_info'

In [15]:
mean_data_df = grouped_data_df.mean()
display(mean_data_df)

                                         info  node_value          pr  \
positive_info positive_value model
False         False          1729   -0.438143  -15.991066   64.653138
                             1777   -0.446468  -15.321635   96.074806
                             1809   -0.330996  -17.194250    0.000000
              True           1729    0.000000   16.532381   83.650373
                             1777    0.000000   16.609883  134.129031
                             1809    0.000000   11.965261    0.000000
True          True           1729   16.610707   22.445396   58.937940
                             1777   18.423387   23.573589   79.500013
                             1809   22.433223   25.825914    0.000000

                                          rpe
positive_info positive_value model
False         False          1729  -29.491083
                             1777  -76.491814
                             1809    2.821963
              True           1729    0.947725
                             1777    0.769703
                             1809   -0.991685
True          True           1729    0.973426
                             1777   -1.028378
                             1809   -1.073186